theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/rainerkaufmann/rainerkaufmann.github.io/master/H61A7473-2_RK1bs_klein.jpg
title: Rainer Kaufmann
description: Experimental Cryo-Photonics Group<br>Centre for Structural Systems Biology<br>Department of Physics<br>University of Hamburg<br><br><img src="https://raw.githubusercontent.com/rainerkaufmann/rainerkaufmann.github.io/master/icon-twitter_gray.png" width="13" height="13"> <a href="https://twitter.com/kaufmannlab/">@KaufmannLab</a><br><br><img src="https://raw.githubusercontent.com/rainerkaufmann/rainerkaufmann.github.io/master/icon-webpage_gray.png" width="13" height="13"> <a href="https://uhh.de/cryofm">uhh.de/cryofm</a>

