theme: jekyll-theme-minimal
logo: https://raw.githubusercontent.com/rainerkaufmann/rainerkaufmann.github.io/master/H61A7473-2_RK1bs_klein.jpg
title: Rainer Kaufmann
description: Experimental Cryo-Photonics Group<br>Centre for Structural Systems Biology<br>Department of Physics<br>University of Hamburg<br><br><img src="https://upload.wikimedia.org/wikipedia/de/thumb/9/9f/Twitter_bird_logo_2012.svg/1200px-Twitter_bird_logo_2012.svg.png" width="20" height="20"><a href="https://twitter.com/kaufmannlab/">@KaufmannLab</a><br><font size="1"> </font><br><a href="https://uhh.de/cryofm">uhh.de/cryofm</a>

